version: '3.8'

services:

  intervisuell-postgres:
    build: ../iv-dev-postgres
    container_name: iv-postgres
    ports:
      - "5432:5432"
    networks:
      - iv-network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      - ${DATAVOLUME}
    restart: unless-stopped

volumes:
  postgres-data:
  data01:

networks:
  iv-network:
    external: true
